// ─── ClawQuestEscrow Contract ABI ────────────────────────────────────────────
// Auto-extracted from Foundry build output. Contains only the functions, events,
// and errors needed by the backend and frontend (no inherited OZ internals).

export const ESCROW_ABI = [
  {
    type: 'function',
    name: 'DEFAULT_ADMIN_ROLE',
    inputs: [],
    outputs: [{ name: '', type: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'OPERATOR_ROLE',
    inputs: [],
    outputs: [{ name: '', type: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'PAUSER_ROLE',
    inputs: [],
    outputs: [{ name: '', type: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'UPGRADER_ROLE',
    inputs: [],
    outputs: [{ name: '', type: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'deposit',
    inputs: [
      { name: 'questId', type: 'bytes32' },
      { name: 'token', type: 'address' },
      { name: 'amount', type: 'uint128' },
      { name: 'expiresAt', type: 'uint64' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'depositNative',
    inputs: [
      { name: 'questId', type: 'bytes32' },
      { name: 'expiresAt', type: 'uint64' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'distribute',
    inputs: [
      { name: 'questId', type: 'bytes32' },
      { name: 'recipients', type: 'address[]' },
      { name: 'amounts', type: 'uint128[]' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'batchDistribute',
    inputs: [
      { name: 'questIds', type: 'bytes32[]' },
      { name: 'recipients', type: 'address[][]' },
      { name: 'amounts', type: 'uint128[][]' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'refund',
    inputs: [{ name: 'questId', type: 'bytes32' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'sponsorEmergencyWithdraw',
    inputs: [{ name: 'questId', type: 'bytes32' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'getQuest',
    inputs: [{ name: 'questId', type: 'bytes32' }],
    outputs: [
      {
        name: '',
        type: 'tuple',
        components: [
          { name: 'sponsor', type: 'address' },
          { name: 'token', type: 'address' },
          { name: 'deposited', type: 'uint128' },
          { name: 'distributed', type: 'uint128' },
          { name: 'refunded', type: 'uint128' },
          { name: 'createdAt', type: 'uint64' },
          { name: 'expiresAt', type: 'uint64' },
          { name: 'cancelled', type: 'bool' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'questBalance',
    inputs: [{ name: 'questId', type: 'bytes32' }],
    outputs: [{ name: '', type: 'uint128' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'isTokenAllowed',
    inputs: [{ name: 'token', type: 'address' }],
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'emergencyGracePeriod',
    inputs: [],
    outputs: [{ name: '', type: 'uint64' }],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    name: 'setTokenAllowed',
    inputs: [
      { name: 'token', type: 'address' },
      { name: 'allowed', type: 'bool' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'initialize',
    inputs: [
      { name: 'admin', type: 'address' },
      { name: 'operator', type: 'address' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'pause',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'unpause',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'paused',
    inputs: [],
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'view',
  },
  // ── Events ──
  {
    type: 'event',
    name: 'QuestFunded',
    inputs: [
      { name: 'questId', type: 'bytes32', indexed: true },
      { name: 'sponsor', type: 'address', indexed: true },
      { name: 'token', type: 'address', indexed: false },
      { name: 'amount', type: 'uint128', indexed: false },
      { name: 'expiresAt', type: 'uint64', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'QuestDistributed',
    inputs: [
      { name: 'questId', type: 'bytes32', indexed: true },
      { name: 'recipients', type: 'address[]', indexed: false },
      { name: 'amounts', type: 'uint128[]', indexed: false },
      { name: 'totalPayout', type: 'uint128', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'QuestRefunded',
    inputs: [
      { name: 'questId', type: 'bytes32', indexed: true },
      { name: 'sponsor', type: 'address', indexed: true },
      { name: 'amount', type: 'uint128', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'EmergencyWithdrawal',
    inputs: [
      { name: 'questId', type: 'bytes32', indexed: true },
      { name: 'sponsor', type: 'address', indexed: true },
      { name: 'amount', type: 'uint128', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'TokenAllowlistUpdated',
    inputs: [
      { name: 'token', type: 'address', indexed: true },
      { name: 'allowed', type: 'bool', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'Paused',
    inputs: [{ name: 'account', type: 'address', indexed: false }],
  },
  {
    type: 'event',
    name: 'Unpaused',
    inputs: [{ name: 'account', type: 'address', indexed: false }],
  },
  // ── Custom Errors ──
  { type: 'error', name: 'ZeroAmount', inputs: [] },
  { type: 'error', name: 'EmptyRecipients', inputs: [] },
  { type: 'error', name: 'LengthMismatch', inputs: [] },
  { type: 'error', name: 'TokenNotAllowed', inputs: [{ name: 'token', type: 'address' }] },
  { type: 'error', name: 'QuestAlreadyFunded', inputs: [{ name: 'questId', type: 'bytes32' }] },
  { type: 'error', name: 'QuestNotFound', inputs: [{ name: 'questId', type: 'bytes32' }] },
  { type: 'error', name: 'QuestCancelled', inputs: [{ name: 'questId', type: 'bytes32' }] },
  { type: 'error', name: 'InsufficientFunds', inputs: [{ name: 'questId', type: 'bytes32' }, { name: 'available', type: 'uint128' }, { name: 'requested', type: 'uint128' }] },
  { type: 'error', name: 'NothingToRefund', inputs: [{ name: 'questId', type: 'bytes32' }] },
  { type: 'error', name: 'NothingToWithdraw', inputs: [{ name: 'questId', type: 'bytes32' }] },
  { type: 'error', name: 'NotSponsor', inputs: [{ name: 'questId', type: 'bytes32' }, { name: 'caller', type: 'address' }] },
  { type: 'error', name: 'NoExpiry', inputs: [{ name: 'questId', type: 'bytes32' }] },
  { type: 'error', name: 'GracePeriodNotElapsed', inputs: [{ name: 'questId', type: 'bytes32' }, { name: 'unlockTime', type: 'uint256' }] },
  { type: 'error', name: 'AlreadyWithdrawn', inputs: [{ name: 'questId', type: 'bytes32' }] },
  { type: 'error', name: 'NativeTransferFailed', inputs: [{ name: 'to', type: 'address' }, { name: 'amount', type: 'uint128' }] },
] as const;
